### ISSUE TITLE
项目维护

### ISSUE THREAD

**Issue by coderchou** [Kssss/LYTFTP#1]
这个项目还维护吗 ，如何区分主动模式和被动模式

**Comment by Kssss** [comment]
我现在去吃了么 送外卖了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"canhua"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 晚上7:10
收件人:&nbsp;"Kssss/LYTFTP"<LYTFTP@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Kssss/LYTFTP] 项目维护 (#1)




这个项目还维护吗 ，如何区分主动模式和被动模式

**Comment by coderchou** [comment]
连大神都转行了，我打算辞职回家种田了😿
